// src/components/Festivals.vue
<script setup>
const festivals = [
  { name: 'Love To Rock', city: 'València', img: 'https://lovetorockfestival.es/wp-content/uploads/2024/12/1366-16.jpg' },
  { name: 'Viña Rock', city: 'Villarrobledo', img: 'https://s10.s3c.es/imag/_v0/1920x1048/a/2/d/EuropaPress_6574901_vina_rock.jpg' },
  { name: 'Medusa', city: 'Cullera', img: 'https://commons.wikimedia.org/wiki/Special:FilePath/Escenario%20principal%20Medusa%20Sunbeach%20Festival%202015.jpg' },
  { name: 'ZEVRA', city: 'Cullera', img: 'https://applications-media.feverup.com/image/upload/f_auto,w_1200,h_900,c_fill/fever2/plan/photo/2a85788a-147e-11f0-b042-c2bd9fb42191.jpg' },
]
</script>

<template>
  <section class="festivals festivals-v3" id="festivales" data-screen-label="04 Festivales">
    <div class="festivals-head v3-head">
      <div>
        <h2 class="section-title section-title--two-lines reveal"><span>Festivales</span><span>con merch vivo</span></h2>
      </div>
    </div>
    <div class="festival-wall">
      <article v-for="(festival, index) in festivals" :key="festival.name" class="festival-poster reveal" data-cursor="hover" :style="{ transitionDelay: `${index * 70}ms` }">
        <img :src="festival.img" :alt="`${festival.name} festival`" loading="lazy" />
        <div class="festival-label">
          <h3>{{ festival.name }}</h3>
          <span>{{ festival.city }} · Online + físico</span>
        </div>
      </article>
    </div>
  </section>
</template>

// festivals.jsx
// festivals.jsx — animated festival posters
const FESTIVALS = [
  { name: 'Love To Rock', city: 'València', img: 'https://lovetorockfestival.es/wp-content/uploads/2025/10/LTR_2026_HOME.jpg' },
  { name: 'Viña Rock', city: 'Villarrobledo', img: 'https://commons.wikimedia.org/wiki/Special:FilePath/Vi%C3%B1a%20rock%202007.jpg' },
  { name: 'Medusa', city: 'Cullera', img: 'https://commons.wikimedia.org/wiki/Special:FilePath/Escenario%20principal%20Medusa%20Sunbeach%20Festival%202015.jpg' },
];

function Festivals() {
  return (
    <section className="festivals festivals-v4" id="festivales" data-screen-label="04 Festivales">
      <div className="festivals-head v3-head">
        <div>
          <div className="section-tag reveal">FESTIVAL SUPPLY</div>
          <h2 className="section-title reveal">Festivales<br/>con merch vivo.</h2>
        </div>
        <p className="section-sub reveal d1">Stands, stock, drops exclusivos, venta física y energía de recinto.</p>
      </div>

      <div className="festival-stage">
        {FESTIVALS.map((f, i) => (
          <article key={f.name} className={`festival-poster-v4 festival-${i} reveal`} style={{ transitionDelay: `${i * 90}ms` }}>
            <span className="tape tape-a"></span>
            <span className="tape tape-b"></span>
            <img src={f.img} alt={`${f.name} festival`} loading="lazy" />
            <div className="festival-label-v4">
              <h3>{f.name}</h3>
              <span>{f.city}</span>
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}

window.Festivals = Festivals;
