// contact.jsx
// contact.jsx — streetwear brief form
function Field({ label, name, type = 'text', value, onChange, textarea, options, required, placeholder }) {
  return (
    <div className="ff">
      <label htmlFor={name} className="ff-label">
        {label}{required && <span className="ff-req">*</span>}
      </label>
      {options ? (
        <select id={name} name={name} value={value} onChange={onChange} className="ff-input" data-cursor="hover">
          <option value="">Selecciona una opción</option>
          {options.map((o) => <option key={o} value={o}>{o}</option>)}
        </select>
      ) : textarea ? (
        <textarea id={name} name={name} value={value} onChange={onChange} rows={5} className="ff-input ff-textarea"
                  placeholder={placeholder} data-cursor="hover" />
      ) : (
        <input id={name} name={name} type={type} value={value} onChange={onChange} className="ff-input"
               placeholder={placeholder} data-cursor="hover" />
      )}
    </div>
  );
}

function Contact() {
  const [form, setForm] = React.useState({ name: '', email: '', phone: '', project: '', need: '', message: '' });
  const [status, setStatus] = React.useState('');
  const upd = (k) => (e) => setForm({ ...form, [k]: e.target.value });

  const submit = (e) => {
    e.preventDefault();
    if (!form.name || !form.email || !form.message) { setStatus('error'); return; }
    setStatus('sending');
    setTimeout(() => setStatus('ok'), 900);
  };

  return (
    <section className="contact contact-v3" id="contacto" data-screen-label="06 Contacto">
      <div className="contact-poster reveal">
        <span className="tape tape-a"></span>
        <img src="https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1300&q=80" alt="Concierto y público" />
        <strong>BRIEF / DROP</strong>
      </div>

      <form className="form-box form-v3 reveal d1" onSubmit={submit}>
        <div className="form-box-head">
          <div className="form-box-tag">Nuevo proyecto</div>
          <h2 className="form-box-title">Cuéntanos tu drop</h2>
          <p className="form-box-sub">Brief rápido, estética de calle y respuesta en menos de 48h.</p>
        </div>

        <div className="form-grid">
          <Field label="Nombre" name="name" value={form.name} onChange={upd('name')} placeholder="Tu nombre" required />
          <Field label="Email" name="email" type="email" value={form.email} onChange={upd('email')} placeholder="tu@email.com" required />
          <Field label="Teléfono" name="phone" type="tel" value={form.phone} onChange={upd('phone')} placeholder="+34 ..." />
          <Field label="Artista / Marca" name="project" value={form.project} onChange={upd('project')} placeholder="Nombre del proyecto" />
          <div className="ff-full">
            <Field label="Qué necesitas" name="need" value={form.need} onChange={upd('need')}
                   options={['Diseño + producción', 'Merch para gira', 'Stand de festival', 'Tienda online', 'Pop-up / activación', 'Todo el 360º']} />
          </div>
          <div className="ff-full">
            <Field label="Brief" name="message" value={form.message} onChange={upd('message')} textarea required
                   placeholder="Fechas, referencias, tipo de prendas, volumen, ideas, estilo..." />
          </div>
        </div>

        <div className="form-cta">
          <div className={`form-status ${status === 'ok' ? 'ok' : status === 'error' ? 'err' : ''}`}>
            {status === 'sending' && 'ENVIANDO...'}
            {status === 'ok' && '✓ BRIEF RECIBIDO — TE ESCRIBIMOS EN 48H'}
            {status === 'error' && '⚠ FALTAN CAMPOS OBLIGATORIOS'}
            {!status && 'Respuesta en menos de 48h'}
          </div>
          <button type="submit" className="btn-primary" data-cursor="hover">ENVIAR BRIEF</button>
        </div>
      </form>
    </section>
  );
}

window.Contact = Contact;

// src/components/Contact.vue
<script setup>
import { reactive, ref } from 'vue'

const form = reactive({ name: '', email: '', phone: '', project: '', need: '', message: '' })
const status = ref('')
const needs = ['Diseño + producción', 'Merch para gira', 'Stand de festival', 'Tienda online', 'Pop-up / activación', 'Todo el 360º']

const submit = () => {
  if (!form.name || !form.email || !form.message) {
    status.value = 'error'
    return
  }
  status.value = 'sending'
  window.setTimeout(() => { status.value = 'ok' }, 900)
}
</script>

<template>
  <section class="contact contact-v3" id="contacto" data-screen-label="06 Contacto">
    <div class="contact-poster reveal">
      <span class="tape tape-a"></span>
      <img src="https://i.pinimg.com/564x/ba/bc/69/babc690344890c4a102d215762edf0d1.jpg" alt="Concierto y público" />
      <!-- <strong>BRIEF / DROP</strong> -->
    </div>

    <form class="form-box form-v3 reveal d1" @submit.prevent="submit">
      <div class="form-box-head">
        <div class="form-box-tag">Nuevo proyecto</div>
        <h2 class="form-box-title">Cuéntanos tu idea</h2>
      </div>

      <div class="form-grid">
        <div class="ff"><label for="name" class="ff-label">Nombre<span class="ff-req">*</span></label><input id="name" v-model="form.name" class="ff-input" placeholder="Tu nombre" data-cursor="hover" /></div>
        <div class="ff"><label for="email" class="ff-label">Email<span class="ff-req">*</span></label><input id="email" v-model="form.email" type="email" class="ff-input" placeholder="tu@email.com" data-cursor="hover" /></div>
        <div class="ff"><label for="phone" class="ff-label">Teléfono</label><input id="phone" v-model="form.phone" type="tel" class="ff-input" placeholder="+34 ..." data-cursor="hover" /></div>
        <div class="ff"><label for="project" class="ff-label">Artista / Marca</label><input id="project" v-model="form.project" class="ff-input" placeholder="Nombre del proyecto" data-cursor="hover" /></div>
        <div class="ff ff-full"><label for="need" class="ff-label">Qué necesitas</label><select id="need" v-model="form.need" class="ff-input" data-cursor="hover"><option value="">Selecciona una opción</option><option v-for="need in needs" :key="need" :value="need">{{ need }}</option></select></div>
        <div class="ff ff-full"><label for="message" class="ff-label">Brief<span class="ff-req">*</span></label><textarea id="message" v-model="form.message" rows="5" class="ff-input ff-textarea" placeholder="Fechas, referencias, tipo de prendas, volumen, ideas, estilo..." data-cursor="hover"></textarea></div>
      </div>

      <div class="form-cta">
        <div class="form-status" :class="{ ok: status === 'ok', err: status === 'error' }">
          <template v-if="status === 'sending'">ENVIANDO...</template>
          <template v-else-if="status === 'ok'">✓ BRIEF RECIBIDO — TE ESCRIBIMOS EN 48H</template>
          <template v-else-if="status === 'error'">⚠ FALTAN CAMPOS OBLIGATORIOS</template>
          <template v-else>Respuesta en menos de 48h</template>
        </div>
        <button type="submit" class="btn-primary" data-cursor="hover">ENVIAR</button>
      </div>
    </form>
  </section>
</template>
