// ticker.jsx
// ticker.jsx — infinite scrolling marquee of artists/festivals
function Ticker({ items }) {
  const content = (
    <span>
      {items.map((it, i) => (
        <React.Fragment key={i}>
          <span>{it}</span>
          <span className="star">✦</span>
        </React.Fragment>
      ))}
    </span>
  );
  return (
    <div className="ticker">
      <div className="ticker-track">
        {content}
        {content}
      </div>
    </div>
  );
}

window.Ticker = Ticker;

// src/components/Ticker.vue
<script setup>
defineProps({ items: { type: Array, required: true } })
</script>

<template>
  <div class="ticker">
    <div class="ticker-track">
      <span v-for="loop in 2" :key="loop">
        <template v-for="item in items" :key="`${loop}-${item}`">
          <span>{{ item }}</span>
          <span class="star">✦</span>
        </template>
      </span>
    </div>
  </div>
</template>
